--- 
apiVersion: v1
kind: Service
metadata: 
  name: apache-service
spec: 
  ports: 
    - nodePort: 30163
      port: 8080
      targetPort: 80
  selector: 
    app: apache
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata: 
    name: apache-pod
    labels:
        app: apache
spec:
    volumes:
      - name: apache-vol
        hostPath: 
          path: "/Users/pschlief/Desktop/kubernetes/git/learn_kubernetes/apache_data"
    containers:
      - name: apache-web
        image: httpd:2.4
        volumeMounts:
          - name: apache-vol
            mountPath: /var/www/html
        ports:
          - containerPort: 80

---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#     name: apache-deployment
# spec:
#      # ich möchte gerne drei Apache-Pods haben
#     replicas: 3
#     strategy: RollingUpdate
#     selector:
#        matchLabels:
#            app: apache
#     template:
#         metadata:
#           labels:
#             app: apache
#         spec:
#           volumes:
#             - name: apache-vol
#               hostPath: 
#                 path: "/Users/pschlief/Desktop/kubernetes/git/learn_kubernetes/apache_data"
#           containers:
#             - name: apache-web
#               image: httpd:2.4
#               volumeMounts:
#                 - name: apache-vol
#                   mountPath: /var/www/html
#               ports:
#                 - containerPort: 80


