
kind: Service
apiVersion: v1
metadata:
  name: hostname-service
spec:
  type: NodePort
  selector:
    app: echo-hostname
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 80
---

kind: Pod
apiVersion: v1
metadata:
  name: hostname-pod-101
  labels:
    app: echo-hostname
    app-version: v101
spec:
  containers:
    - name: nginx-hostname
      image: kubegoldenguide/nginx-hostname:1.0.1
      ports:
        - containerPort: 80

---

kind: Pod
apiVersion: v1
metadata:
  name: hostname-pod-102
  labels:
    app: echo-hostname
    app-version: v101
spec:
  containers:
    - name: nginx-hostname
      image: kubegoldenguide/nginx-hostname:1.0.2
      ports:
        - containerPort: 80