#try to irgendwas einen apache-webserver
#https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml
--- 
apiVersion: v1
kind: Service
metadata: 
  name: apache-service
spec:
  type: NodePort
  selector: 
    app: apache
  ports: 
    - nodePort: 30163
      port: 8080
      targetPort: 80
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: apache-persistant-volume
spec: 
  accessModes: 
      - ReadWriteOnce
  capacity: 
    storage: 128M
  hostPath: 
    path: /Users/pschlief/Desktop/kubernetes/apache_data
    


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apache-pvc
spec:
    resources:
        requests:
            storage: 64M
    accessModes:
      - ReadWriteOnce

---

kind: Pod
apiVersion: v1
metadata: 
    name: apache-pod
    labels:
        app: apache
spec:
    volumes:
     volumeMounts:
        - name: apache-pod-persistant-volume
          persistantVolumeClaim:
          claimName: apache_pvc
         
   
    containers:
      - name: apache-web
        image: httpd:2.4
        volumeMounts:
          - name: apache-pod-persistant-volume
            mountPath: /var/www/html
        ports:
          - containeport: 80
          mountPath: /var/www/html

---

kind: Deployment
apiversion: v1
metadata:
    name: apache-deployment
spec:
     # ich möchte gerne drei Apache-Pods haben
    replicas: 3
    strategy: RollingUpdate
    selector:
       matchLabels:
           app: apache
