kind: Pod
apiVersion: v1
metadata:
  name: websrv-pod
  labels:
    application-name: database-project
    tier: frontend
spec:
  containers:
    - name: websrv-cont
      image:  webdevops/php-apache
      ports:
        - containerPort: 80